# Generated by Django 6.0.2 on 2026-02-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликованно"),
                ),
                (
                    "total_likes",
                    models.PositiveIntegerField(default=0, verbose_name="Всего лайков"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата лайка"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="videos.video",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк",
                "verbose_name_plural": "Лайки",
            },
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="videos/", verbose_name="Видео файл"),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("HD", "HD (720p)"),
                            ("FHD", "FHD (1080p)"),
                            ("UHD", "UHD (4K)"),
                        ],
                        max_length=3,
                        verbose_name="Качество",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="videos.video",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео файл",
                "verbose_name_plural": "Видео файлы",
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="videos_vide_is_publ_903adb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["owner", "is_published"], name="videos_vide_owner_i_e7abfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["video", "user"], name="videos_like_video_i_98c79f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("video", "user"), name="unique_video_user_like"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videofile",
            unique_together={("video", "quality")},
        ),
    ]
